// Code generated by "stringer -type Op"; DO NOT EDIT.

package gomodel

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[OpInsert-1]
	_ = x[OpUpdate-2]
	_ = x[OpSelect-4]
	_ = x[OpDelete-8]
}

const (
	_Op_name_0 = "OpInsertOpUpdate"
	_Op_name_1 = "OpSelect"
	_Op_name_2 = "OpDelete"
)

var (
	_Op_index_0 = [...]uint8{0, 8, 16}
)

func (i Op) String() string {
	switch {
	case 1 <= i && i <= 2:
		i -= 1
		return _Op_name_0[_Op_index_0[i]:_Op_index_0[i+1]]
	case i == 4:
		return _Op_name_1
	case i == 8:
		return _Op_name_2
	default:
		return "Op(" + strconv.FormatInt(int64(i), 10) + ")"
	}
}
